const DEFAULT_STATIONS = [
  {
    id: 1,
    url: 'https://www.youtube.com/watch?v=I24GTW0O_hc&t=18s',
    thumbnail: 'https://img.youtube.com/vi/I24GTW0O_hc/maxresdefault.jpg',
    title: 'Lo-fi Chill Music',
  },
  {
    id: 2,
    url: 'https://www.youtube.com/watch?v=xGmbvFkjzGM',
    thumbnail: 'https://img.youtube.com/vi/xGmbvFkjzGM/maxresdefault.jpg',
    title: 'Classical Piano Music',
  },
  {
    id: 3,
    url: 'https://www.youtube.com/watch?v=i3qIAZr-iWU',
    thumbnail: 'https://img.youtube.com/vi/i3qIAZr-iWU/maxresdefault.jpg',
    title: 'Jazz Relaxing Music',
  },
];

export default DEFAULT_STATIONS;
